# Generated by Django 4.2.7 on 2023-12-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasjamlaoui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='extra_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(default='employee', max_length=50),
        ),
    ]
