# Generated by Django 4.2.7 on 2023-12-17 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anasjamlaoui', '0002_employee_extra_bonus_employee_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anc_title', models.CharField(max_length=100)),
                ('anc_description', models.CharField(max_length=1000)),
                ('anc_date', models.DateField()),
                ('anc_admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anasjamlaoui.employee')),
            ],
        ),
    ]
